### PR TITLE
Allow code line numbering with a `:numbers` suffix to language name

### PR DESCRIPTION
**Pull request by raphink**
Example (using the `commonmarker` markdown engine and `github-gist` style):

``````
```yaml:numbers                                                                 
  ---                                                                             
  apiVersion: v1                                                                  
  kind: Pod                                                                       
  metadata:                                                                       
    name: producer                                                                
  spec:                                                                           
    containers:                                                                   
    - name: producer                                                              
      image: producer                                                             
    nodeSelector:                                                                 
      cpuclass: high                                                              
```       
``````

Result:

screenshot from 2018-11-02 16-09-18

### CODE REVIEW

**Comment by raphink** [comment]
Good point. I wasn't aware of the `execute` flag, and I can't use it with the Commonmarker engine it seems.

It seems the problem you're highlighting can be simply solved with CSS. However, I think these features should work in a similar way, so I'd like to standardize `execute` to work with Commonmarker as well.

Looking at the [Commonmark spec](https://spec.commonmark.org/0.12/#fenced-code-blocks) only the first word in the info string is parsed, which is why I need to use a colon instead of a space. However, that's not how Showoff's `@@@` syntax works.

What do you think should be done to standardize this?

**Comment by raphink** [comment]
From what I read on various projects, some Markdown (not Commonmark-compliant) engines do read multiple words in the info string as additional classes. Others use `?` for arguments, similar to what I've done with `:`:

``````markdown
```lang?args
some code
```
``````

In either case, highlightjs ignores both `?` and `:` and renders the code properly, so we just need Showoff to analyze the class name to extract the args. However at the moment, the `execute` option requires to place an `execute` class on the block, which is not possible with Commonmark.

I'm guessing a `?args` syntax would also work with the Showoff interpreter, since it would generate the same HTML DOM as the Commonmark interpreter, and the features (both `execute` and `numbers`) would be interpreted in showoff.js.

**Comment by raphink** [comment]
I've been playing around with this in showoff.js:

```javascript
      var langOptsStr = $(block).attr("class").match(/\blanguage-\w+\?(\S+)/);                   
      if (langOptsStr != undefined) {                                         
        var langOpts = langOptsStr[1].split("&");                             
                                                                           
        for(i=0; i<langOpts.length; i++) {                                 
          console.log("Adding class "+langOpts[i]);                        
          $(block).addClass(langOpts[i]);                                  
        }                                                                  
      }     
```

**Comment by binford2k** [comment]
The spec is surprisingly lenient in that regards.

> The first word of the info string is typically used to specify the language of the code sample, and rendered in the class attribute of the code tag. However, this spec does not mandate any particular treatment of the info string.

That said, I would like to avoid deviating just for the sake of deviating.

Additional words in the info string are used all throughout Showoff as classes on the block for styling. If we did convert it to use colon separators or a ? delimited arg string, we'd also have to propagate the tokens up to classes to retain existing behavior. It looks like that's what your snippet does, promotes `lang?arg1&arg2&arg3` to classes. I really don't like that syntax though. It feels like a *programming language* rather than a document format. Would it be possible to just ensure that any space delimited arguments get promoted? `lang arg1 arg2 arg3` seems far more approachable and is more consistent with other argument strings in the presentation (everything else is space delimited and either `arg` or `arg=value`).

I haven't worked much with the Commonmarker engine. Does it just throw away any remaining arguments in the info string? Where could those be captured?

**Comment by raphink** [comment]
@binford2k 	I agree that space-separated would be cleaner. However cmark simply *ignores* anything after the first word in the info string, in accordance with the spec, so it doesn't seem possible to use that data unless we patch the cmark lib…

**Comment by binford2k** [comment]
I reworked the class matching to correlate with the munging PR from the other day. I've validated the numbering on commonmarker and redcarpet and both seem to work. Can you validate that it meets your needs?

**Pull request merged**
