### PR TITLE
Add commonmark support to Dockerfile

### PR DESCRIPTION
**Pull request by raphink**

### CODE REVIEW

**Comment by binford2k** [comment]
what's the resulting image size?

**Comment by raphink** [comment]
The image is published on https://hub.docker.com/r/camptocamp/showoff/ if you want to check

**Comment by raphink** [comment]
It says 124 MB... Only because of that one change?

**Comment by raphink** [comment]
Or should we purge all of cmake's dependencies manually? No equivalent to apt's autoremove?

**Comment by raphink** [comment]
Great, thanks @binford2k !

**Pull request merged**
