### PR TITLE
remove getnotestext function, because really

### PR DESCRIPTION
**Pull request by marrero984**

### CODE REVIEW

**Comment by binford2k** [comment]
because really what?

**Comment by marrero984** [comment]
@binford2k it was called in a single place and all it returned was getCurrentNotes.text(). Unnecessary abstraction

**Comment by binford2k** [comment]
Merge this when ready to make a breaking release, since it changes the js API

**Comment by binford2k** [comment]
Question about this before merging. When do we want to expose the `#notes` element to the end user? Should that remain a private member? If it's exposed in an "api" then we're saying use it. If the user has to retrieve it themselves with `$("#notes")`, then it's clear that we're allowed to break it if needed.

**Comment by binford2k** [comment]
I think I'm actually going to leave this in.

**Pull request closed without merging**
