### PR TITLE
Copy all background properties

### PR DESCRIPTION
**Pull request by binford2k**
This still doesn't look completely right on complex background images.

### CODE REVIEW

**Comment by marrero984** [comment]
@binford2k I was already working on this and you're supposed to be on vacation!

**Comment by marrero984** [comment]
```
    /* background-size reduced because the transform is applied at the .content
       level and not at the .container level */
    $('#nextSlide .container')
      .html(nextSlide.html())
      .css({
        'background-image':    nextSlide.css('background-image'),
        'background-size':     parseInt(nextSlide.css('background-size')) / 2,
        'background-repeat':   nextSlide.css('background-repeat'),
        'background-position': nextSlide.css('background-position')
      });
    $('#prevSlide .container')
      .html(nextSlide.html())
      .css({
        'background-image':    prevSlide.css('background-image'),
        'background-size':     parseInt(prevSlide.css('background-size')) / 2,
        'background-repeat':   prevSlide.css('background-repeat'),
        'background-position': prevSlide.css('background-position')
      });
```

**Comment by binford2k** [comment]
I arrived earlier than the rest of the crew and needed to get inside for a
while out of the sun :)

**Comment by binford2k** [comment]
@marrero984 `parseInt(nextSlide.css('background-size')) / 2` only works for a single width (in px) property though, yeah?

**Pull request merged**
