### PR TITLE
repositioned to left of question in notes display

### PR DESCRIPTION
**Pull request by marrero984**

### CODE REVIEW

**Comment by marrero984** [comment]
screen shot 2015-12-11 at 10 48 08 am

**Comment by binford2k** [comment]
That's way too small. It's like a quarter of the size that it was!

**Comment by marrero984** [comment]
Based on custom CSS, not on base showoff
screen shot 2015-12-14 at 5 26 29 pm

**Comment by marrero984** [comment]
Final

screen shot 2015-12-15 at 9 30 04 am

**Pull request merged**
