### PR TITLE
Change syntax highlighting library to a maintained project

### PR DESCRIPTION
**Pull request by binford2k**
shjs has been unmaintained since 2008. Highlight.js is actively
maintained and has a much much larger library of supported languages.
This commit includes an uncompressed build of _all_ supported languages.

The final release will likely have a smaller build, with selected
languages and minified.

This is incomplete. The highlighting fails. But I need to shelf it for
now and move on to another project.

@marrero984 if you're looking for a project, debugging the js would be welcomed.

### CODE REVIEW

**Comment by binford2k** [comment]
I should point out that the library I'm trying is https://github.com/isagalaev/highlight.js

**Comment by marrero984** [comment]
core.js and showoffcore.js are the problem.  Yanked them from my local and only broke the style menu.

**Comment by marrero984** [comment]
Also, changing to this library will require updating all slides that use "@@@ Shell" to "@@@ Bash"

**Comment by binford2k** [comment]
Actually, the plan is to add new styles, one of which is Shell or Terminal to represent command line entry.

**Comment by binford2k** [comment]
Wait, this worked? And highlighted? I'm almost certain I'd tried that. I removed js on at a time until it was down to bare minimum!

**Comment by marrero984** [comment]
closing in favor of separate pull requests: one to remove broken style switching functionality, the other to change syntax highlighting libraries

**Pull request closed without merging**
